### ISSUE TITLE
Step order difference between code and algorithm in paper

### ISSUE THREAD

**Issue by yenchenlin** [openai/imitation#4]
Hello @hojonathanho,

does the code [here](https://github.com/openai/imitation/blob/master/policyopt/imitation.py#L476-L498) swapped the order of **step 4.** and **step 5.** of the algorithm presented in the paper?

<img width="657" alt="screen shot 2016-09-08 at 11 07 03 am" src="https://cloud.githubusercontent.com/assets/7057863/18336528/8021d8ea-75ba-11e6-8445-46bec156f451.png">

**Comment by hojonathanho** [comment]
I've experimented with both orderings, and I found no significant difference in performance.
